name: py3_9_neuralReranker1_0
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.1=pyhc872135_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.9.23=he99959a_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - accelerate==1.8.1
      - addict==2.4.0
      - aiofiles==22.1.0
      - aiosqlite==0.21.0
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - blinker==1.9.0
      - blis==1.3.0
      - braceexpand==0.1.7
      - cachetools==6.1.0
      - catalogue==2.0.10
      - certifi==2025.6.15
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cloudpathlib==0.21.1
      - comm==0.2.2
      - confection==0.1.5
      - contexttimer==0.3.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - cymem==2.0.11
      - debugpy==1.8.14
      - decorator==4.4.2
      - decord==0.5.2
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - diffusers==0.16.0
      - distlib==0.3.9
      - easydict==1.9
      - einops==0.8.1
      - entrypoints==0.4
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fairscale==0.4.4
      - fastapi==0.115.14
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.58.4
      - fqdn==1.5.1
      - fsspec==2025.5.1
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.25.2
      - identify==2.6.12
      - idna==3.10
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iopath==0.1.10
      - ipykernel==6.29.5
      - ipython==8.18.1
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.1
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==7.4.9
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-packaging==0.12.3
      - jupyter-server==2.16.0
      - jupyter-server-fileid==0.9.3
      - jupyter-server-terminals==0.5.3
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.8
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kaggle==1.7.4.5
      - kiwisolver==1.4.7
      - langcodes==3.5.0
      - language-data==1.3.0
      - lazy-loader==0.4
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - moviepy==1.0.3
      - mpmath==1.3.0
      - murmurhash==1.0.13
      - narwhals==1.44.0
      - nbclassic==1.3.1
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - nltk==3.9.1
      - nodeenv==1.9.1
      - notebook==6.5.7
      - notebook-shim==0.2.4
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - open3d==0.14.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.5.5.64
      - opendatasets==0.1.22
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.10.0
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.8
      - plotly==6.2.0
      - portalocker==3.2.0
      - pre-commit==4.2.0
      - preshed==3.0.10
      - proglog==0.1.12
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - protobuf==6.31.1
      - psutil==7.0.0
      - psycopg2==2.9.10
      - psycopg2-binary==2.9.10
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pycocoevalcap==1.2
      - pycocotools==2.0.10
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - python-magic==0.4.27
      - python-multipart==0.0.20
      - python-slugify==8.0.4
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyyaml-env-tag==0.1
      - pyzmq==27.0.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.4
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rpds-py==0.25.1
      - safetensors==0.5.3
      - salesforce-lavis==1.0.1
      - scikit-image==0.24.0
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.1.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.7
      - spacy==3.8.7
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.5.1
      - stack-data==0.6.3
      - starlette==0.46.2
      - streamlit==1.46.1
      - sympy==1.14.0
      - tenacity==9.1.2
      - terminado==0.18.1
      - text-unidecode==1.3
      - thinc==8.3.6
      - threadpoolctl==3.6.0
      - tifffile==2024.8.30
      - timm==0.4.12
      - tinycss2==1.4.0
      - tokenizers==0.13.3
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.33.2
      - triton==3.3.1
      - typer==0.16.0
      - types-python-dateutil==2.9.0.20250516
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.5.0
      - uvicorn==0.35.0
      - virtualenv==20.31.2
      - wasabi==1.1.3
      - watchdog==6.0.0
      - wcwidth==0.2.13
      - weasel==0.4.1
      - webcolors==24.11.1
      - webdataset==0.2.100
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - widgetsnbextension==4.0.14
      - wrapt==1.17.2
      - y-py==0.6.2
      - ypy-websocket==0.8.4
      - zipp==3.23.0
prefix: /home/bharati/anaconda3/envs/py3_9_neuralReranker1_0
